language: python
python:
  - "2.7"
env:
  - PGVERSION=9.2
sudo: required
cache: pip
install:
    - ./bin/travis-install-dependencies
    - pip install coveralls
script: ./bin/travis-run-tests
after_success:
    - coveralls
